### ISSUE TITLE
Output directory incorrect

### ISSUE THREAD

**Issue by ckao10301** [TemryL/ComfyS3#10]
@TemryL  In the .env, I used "output" as the output directory.

But when the file is saved, it's not saved to the "output" folder. Instead "output\" is added as a prefix to the file name. What am I doing wrong?

![image](https://github.com/TemryL/ComfyS3/assets/129625358/4b62d13a-cb59-4f54-a626-a15ac015f73f)
![image](https://github.com/TemryL/ComfyS3/assets/129625358/24900d4f-495d-4a25-bf48-eacf0dec5fa4)

**Comment by ppvolto** [comment]
Do you use Windows or the Windows Subsystem for Linux?

**Comment by ckao10301** [comment]
Windows comfy portable edition.

**Comment by ppvolto** [comment]
The Problem is that Windows uses the `\` as path separator and urls and Linux use the `/` for that task. So that is a Bug in the filename generation

**Comment by ckao10301** [comment]
> The Problem is that Windows uses the `\` as path separator and urls and Linux use the `/` for that task. So that is a Bug in the filename generation

thanks, I decided to work in linux instead.
