### ISSUE TITLE
Save to jpeg before uploading?

### ISSUE THREAD

**Issue by ckao10301** [TemryL/ComfyS3#11]
@TemryL I've been using the Image Save node from WAS suite to convert images to jpg and remove metadata before saving. Is there any way to use this with the save to s3 node?

![image](https://github.com/TemryL/ComfyS3/assets/129625358/3951a6a7-8151-4bd5-bde5-8983502b8957)

**Comment by ckao10301** [comment]
Hi @TemryL just wondering what are you thoughts on this?

**Comment by jiangdi0924** [comment]
It is very useful to resize images before they are uploaded

**Comment by EmmanuelMr18** [comment]
Looks that new WAS nodes can return the images, so you can do this:
I don't think that something needs to change to achieve this use case.

![image](https://github.com/TemryL/ComfyS3/assets/31712515/d38468ff-8833-4e02-bb9c-bdca83626c4d)

**Comment by ckao10301** [comment]
@EmmanuelMr18 I tried that exactly before, and it still uploaded as png, not jpg. I will test it again and report results.

**Comment by TemryL** [comment]
> @EmmanuelMr18 I tried that exactly before, and it still uploaded as png, not jpg. I will test it again and report results.

Yes, the save image to s3 has basically the same logic that the original save image node from comfy. It basically save the image locally in a temp file, upload the temp file to s3 and finally remove the temp file. If we want to have all the options from the WAS node we could take the node and apply the same logic (save temp file, upload temp file, remove temp file).

**Comment by TemryL** [comment]
> Looks that new WAS nodes can return the images, so you can do this: I don't think that something needs to change to achieve this use case.
> 
> ![image](https://private-user-images.githubusercontent.com/31712515/346409682-d38468ff-8833-4e02-bb9c-bdca83626c4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTE3NzQsIm5iZiI6MTcyMDQxMTQ3NCwicGF0aCI6Ii8zMTcxMjUxNS8zNDY0MDk2ODItZDM4NDY4ZmYtODgzMy00ZTAyLWJiOWMtYmRjYTgzNjI2YzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA0MDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MjFhOTk2NGI5MjViYjBmYjAxZDRkMmE0ZDkyN2NkODU2ODgyOGMyNDczOGE2ZThmNjE3N2E3NGNhM2U3Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SzdCYbOcRtHO20xM8ve3kIE-PBQKvzNZbDHGZ15wZhY)

Unfortunately, I don't think this would solve the issue as the node most likely return the image data and not the actual file generated by the node.

**Comment by ckao10301** [comment]
@TemryL I tried to follow but got a little lost haha. How difficult would it be to integrate these 2, and is this something you'd be able to support? Unfortunately I can't code but otherwise I'd help with this.

**Comment by TemryL** [comment]
> @TemryL I tried to follow but got a little lost haha. How difficult would it be to integrate these 2, and is this something you'd be able to support? Unfortunately I can't code but otherwise I'd help with this.

Should be straightforward, I'll have a look at WAS code and try to add the node asap

**Comment by ckao10301** [comment]
Awesome thanks!

**Comment by ckao10301** [comment]
Hi @TemryL wondering if there are any updates?

**Comment by ckao10301** [comment]
Hi @TemryL just following up again

**Comment by TemryL** [comment]
Hi @ckao10301, sorry I forgot to answer. I looked at it and it appeared to be a bit harder than I expected. What about using the upload file s3 node after using the WAS node?

**Comment by ckao10301** [comment]
Yea, I tested again and as we discussed before when connecting WAS Image
Save node to s3 save node, even though WAS saves as jpeg, s3 uploads png
instead.

WAS Node Suite: Image file saved to:
/home/novato/Desktop/ComfyUI/output/2024-07-26/ComfyUI_0003.jpeg
Executed {'node': '276', 'output': {'images': [{'filename':
'ComfyUI_0003.jpeg', 'subfolder': '2024-07-26', 'type': 'output'}]},
'prompt_id': '7587a059-6305-4114-881c-ee598710fc56'}
Prompt executed in 9.97 seconds
Executed {'node': '277', 'output': {'images': [{'filename':
'Image_00033_.png', 'subfolder': '', 'type': 'output'}]}, 'prompt_id':
'7587a059-6305-4114-881c-ee598710fc56'}
Executed {'node': '278', 'output': {'text': ['output/Image_00033_.png']},
'prompt_id': '7587a059-6305-4114-881c-ee598710fc56'}

I agree modifying WAS node is a better idea. I will open an issue on the
WAS repo and cc you in case they have any questions, does that work?

**Comment by ckao10301** [comment]
I added an issue to WAS repo: https://github.com/WASasquatch/was-node-suite-comfyui/issues/444

**Comment by TemryL** [comment]
I meant using the upload file to s3 node and not save to s3 node. The save node to s3 will always upload save and upload a png. I guess the image output of the WAS node is just the image data and not the actual jpeg file. I checked the WAS node and it does not return the local path. I will open a pull request and cc you. Then we can add the option to delete the file after upload in the upload to s3 node.

**Comment by TemryL** [comment]
With this last [commit](https://github.com/TemryL/ComfyS3/commit/952d8921354048d2a2a1aedd115c9ace32c1273c) and this [PR](https://github.com/WASasquatch/was-node-suite-comfyui/pull/445), you should be able to upload file generated by WAS save image node and delete the local file if needed. 
<img width="1003" alt="Screenshot 2024-07-26 at 09 27 47" src="https://github.com/user-attachments/assets/9acf117c-48f5-44e8-b67a-499adcfa641e">

**Comment by ckao10301** [comment]
@TemryL that works, thanks! Is it possible to transfer the "filename_prefix" input and "s3_image_paths" output to the Upload File to S3 node from the Save Image to S3 node? Those are critical to my workflow.

![image](https://github.com/user-attachments/assets/bb8fec38-e533-4c6a-9911-53497645852c)

**Comment by TemryL** [comment]
Yes I can return de s3 path as well, however I guess the file prefix should be controlled directly in the was node

**Comment by ckao10301** [comment]
Great that makes sense.

**Comment by ckao10301** [comment]
you are awesome, thank you
