### ISSUE TITLE
What's a good way to get the S3 URL after saving video files to S3? 

### ISSUE THREAD

**Issue by cbsudux** [TemryL/ComfyS3#16]
Hi,

What's a good node/approach to retrieve the S3 URL of the saved file?

**Comment by TomySpagnoletti** [comment]
Like this:
<img width="777" alt="Screenshot 2024-07-30 at 14 49 31" src="https://github.com/user-attachments/assets/b85c7cbb-3baa-4932-8cae-9fe0d662bc2d">

Then you can use a String Selector to do what you need.

**Comment by woutrbe** [comment]
Sorry to open this again, which node are you using there to read the `path`? I'd like to combine this with a webhook node, but struggling to read the value.

**Comment by TomySpagnoletti** [comment]
I hope it will help you:
<img width="1666" alt="Screenshot 2024-11-23 at 22 26 19" src="https://github.com/user-attachments/assets/22be728e-bd28-418c-b358-14357038f59e">
