### ISSUE TITLE
Add UUID subfolder to prevent overwriting?

### ISSUE THREAD

**Issue by ckao10301** [TemryL/ComfyS3#18]
Currently, all files are uploaded to a single output folder in s3. My output folder is called "output". But files can be overwritten when they have the same name, which is becoming frequent for me. I could add a very long random prefix to each file name, like 12312301923810923.jpg, but then the file name starts to look very long and ugly, especially since my users download their files. Is there a way to save each group of files in their own UUID subfolder to prevent overwriting?

For example, if there are 3 outputs for a single run, they would be saved to 

output/550e8400-e29b-41d4-a716-446655440000/file1.jpg
output/550e8400-e29b-41d4-a716-446655440000/file2.jpg
output/550e8400-e29b-41d4-a716-446655440000/file3.jpg

Each subsequent run, the UUID subfolder would change.

Currently, the output names look like this.

![image](https://github.com/user-attachments/assets/3acecc9b-118b-4de1-8470-fd0f57c966f9)

**Comment by TemryL** [comment]
So you would like to have one UUID per workflow or per user?

**Comment by ckao10301** [comment]
For each new run not per user. So everytime a workflow is run, comfys3
uploads to a new UUID subfolder. I'm running via api so there's no way to
identify users.

**Comment by ckao10301** [comment]
I'm currently Upload File to S3 for images and Save Video Files to S3 for video. Is there a way to combine these nodes so you don't have to duplicate your changes across all of the save nodes?

![image](https://github.com/user-attachments/assets/2e3cc02e-ec96-4ab9-9c6b-707b1c77cf38)

**Comment by TemryL** [comment]
Yes, I think we need to create a PR as we did with was node. The save video node is basically the one from https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite. Can you check first if the nodes from Kosinkadink returne filenames, and if not can you open an issue and tag me?

**Comment by ckao10301** [comment]
@TemryL tagged you on https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues/271

**Comment by TemryL** [comment]
@ckao10301 just made this [PR](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/pull/272). If merged, the paths will be return by `Filenames (string)` output.

**Comment by ckao10301** [comment]
thank you so much!

**Comment by ckao10301** [comment]
After update to VHS develop branch, VHS connects to Upload File to S3 node and uploads successfully.

![image](https://github.com/user-attachments/assets/2bcac1f0-8ea2-4fc3-a538-b9de0962f640)

**Comment by ckao10301** [comment]
I guess that unlocks the next step?

> @TemryL I had an idea. Maybe add an input that allow us to specify the name of the subfolder? That would solve several problems, including another one I've been having.
> 
> 1. Could input a random text to be used as UUID
> 2. Can specify specific subfolder name. For example, if I have an image workflow, I want it to be saved to the "images" subfolder. For video workflows, I want them to be saved to the "video" subfolder. So the node can take a text input "image" or "video" as a way of specifying the subfolder name

**Comment by ckao10301** [comment]
tried S3_OUTPUT_DIR = "output/video". still saved to output/aaaaa_00001.mp4 so I guess it didn't work.

**Comment by TemryL** [comment]
Can you try using the node argument and not the env var? I think the env var is not used in the code and should be removed

**Comment by ckao10301** [comment]
sure, how do I use the node argument? also this doesn't solve the UUID use
case would it?

**Comment by ckao10301** [comment]
@TemryL I was able to get the node argument to work. In that case, I can use random text and concatenate nodes to generate the UUID subfolder path. Thanks
