### ISSUE TITLE
ComfyS3 node is not visible in ComfyUI

### ISSUE THREAD

**Issue by jaikumarbhatt** [TemryL/ComfyS3#2]
ComfyS3 node is not visible in ComfyUI  after so many times restart the server and update the node from comfyui manager, what i do and one more important thing i also update the details in .env file

**Comment by TemryL** [comment]
Hey, thanks for your feedback. I was not able to reproduce your issue. Maybe try a fresh restart and install ComfyS3 manually (assuming your Python env for ComfyUI is activated):

```bash
git clone https://github.com/comfyanonymous/ComfyUI.git
cd ComfyUI/custom_nodes
git clone https://github.com/TemryL/ComfyS3
cd ComfyS3
pip install -r requirements.txt
cd ..
cd ..
python main.py
```

Let me know if that works.
