### ISSUE TITLE
backblaze s3 api supported?

### ISSUE THREAD

**Issue by ckao10301** [TemryL/ComfyS3#3]
Backblaze has an s3 compatible api. Is this supported? Maybe the .env needs s3_endpoint instead of s3_region?

My backblaze endpoint looks like this: https://s3.us-east-005.backblazeb2.com

https://www.backblaze.com/docs/en/cloud-storage-call-the-s3-compatible-api?highlight=undefined

It's 5x cheaper than amazon s3 and egress is free up to a limit

**Comment by ckao10301** [comment]
Hi @TemryL just following up.

**Comment by TemryL** [comment]
Hi @ckao10301, thanks for your feedback! Do you have any idea on how we should implement this ?

**Comment by ckao10301** [comment]
@TemryL 
I found this documentation: https://www.backblaze.com/apidocs/s3-put-object
Does that help? 
I'm not a developer though so I don't know exactly how to implement this. But happy to test things out.

**Comment by TemryL** [comment]
Ill have a look, thanks !

**Comment by ckao10301** [comment]
Hi Tom,

Just wondering if there any updates.

Thanks,

Calvin

**Comment by TemryL** [comment]
Hi @ckao10301, could you please let me know if the last PR works with backblaze? Thanks!

**Comment by ckao10301** [comment]
Getting this error. Did I set up the .env correctly?

![Untitled](https://github.com/TemryL/ComfyS3/assets/129625358/211b309a-3749-4cf4-96bb-9b02ad496e49)

![image](https://github.com/TemryL/ComfyS3/assets/129625358/be9d1dac-4835-4876-8d52-32dcd9daf7f7)

**Comment by TemryL** [comment]
Hi @ckao10301, were you able to make it work with backblaze?

**Comment by ckao10301** [comment]
Yes i added details in previous comment. Thanks
